### ISSUE TITLE
Can't open the Sketch file

### ISSUE THREAD

**Issue by fabianhenzler** [teracyhq/bootflat-ui-kit-sketch#3]

**Comment by jmleapline** [comment]
Same problem here - I'm using the 3.1 beta version.

**Comment by sirme87** [comment]
That's pretty weird. I tried to download the file and opened it with Sketch 3.1 & 3.2 with no problem. I gonna investigate more. 
In the meantime, please try to download the file here: https://www.dropbox.com/s/xvi8g8b688yx7kz/Bootflat%20Sketch.sketch?dl=0

If you still get the problem, pls tell us. 
Thanks for your feedbacks!

**Comment by jmleapline** [comment]
Just an update, I downloaded the non-beta version (3.2.2) and it opened up fine.

**Comment by hoatle** [comment]
@fabianhenzler could you tell us the exact version you used?

**Comment by jmleapline** [comment]
The one that didn't open up was Version 3.1 (8603). It was a beta version.

**Comment by fabianhenzler** [comment]
I'm using the most recent AppStore Version of Sketch

**Comment by kamelury** [comment]
Same problem with Sketch version 3.3 (11970)

**Comment by sirme87** [comment]
OK, I think I found the issue here.

Because the github branch was named as "bootflat-ui-kit.sketch" so when you downloaded the zip and extracted, you got a _sketch file_ instead of _a folder_.

We will correct the branch name. In the mean time, after extracting the zip, try to rename "bootflat-ui-kit.sketch" to "bootflat-ui-kit.zip" and extract it. You can also download the sketch file only from this link:
https://www.dropbox.com/s/xvi8g8b688yx7kz/Bootflat%20Sketch.sketch?dl=0

Tell me if it works for you.

**Comment by kamelury** [comment]
Yes! That was it. Thank you :)

**Comment by hoatle** [comment]
the repo was renamed from https://github.com/teracyhq/bootflat-ui-kit.sketch to https://github.com/teracyhq/bootflat-ui-kit-sketch

it should work now, so I close this.
